trigger:
- development
- uat
- master

pool:
  name: LinuxAgentPool
  demands:
    - JDK -equals 11
    - Terraform -equals Yes
    - Agent.Name -equals ADOAgent

variables:
  global_version: '1.0.0'
  global_email: 'mavrick202@gmail.com'
  azure_dev_sub: '9ce91e05-4b9e-4a42-95c1-4385c54920c6'
  azure_prod_sub: '298f2c19-014b-4195-b821-e3d8fc25c2a8'
  isDev: $[eq(variables['Build.SourceBranch'], 'refs/heads/dev')]
  isProd: $[eq(variables['Build.SourceBranch'], 'refs/heads/production')]

stages:
- stage: CheckingTheAgent
  condition: and(succeeded(), eq(variables.isDev, true))
  pool:
    name: LinuxAgentPool
    demands:
     - Terraform -equals Yes
  variables:
    stage_version: '2.0.0'
    stage_email: 'raghusaran19@gmail.com'
  jobs:
  - job: CheckingTerraformAndPackerAndAnsibleAndTrivy
    variables:
      job_version: '3.0.0'
      job_email: 'sraghu486@gmail.com'
    timeoutInMinutes: 5
    steps:
      - script: echo $(Build.BuildId)
        displayName: 'Display The Build-ID'
      - script: terraform version && packer version && ansible --version && trivy --version
        displayName: 'Display Terraform & Packer Version'
      - script: docker version && docker ps && docker images && docker ps -a
        displayName: 'Display Docker Version'
      - script: pwd && ls -al
        displayName: 'List Folder & Files'
